### ISSUE TITLE
colcon build failing when approaching champ_msgs with ros2 humble working on ros2 branch

### ISSUE THREAD

**Issue by physicsfreak963** [chvmp/champ#137]
I'm 90% sure it's a problem with rosidl, but tried everything i found on the internet nothing worked, especially when running 'colcon build' without sudo I'm getting windows saying rosidl different packages are crushing. bare in mind I'm running on 32 gb of ram so i don't know at this point what the issue is (as in I doubt it's a memory issue)
---
``:~/champ-ws$` sudo colcon build
Starting >>> champ   
Starting >>> champ_msgs
Starting >>> champ_description
Starting >>> champ_config
Starting >>> champ_navigation
Starting >>> champ_teleop
Finished <<< champ_description [0.44s]                      
Finished <<< champ_config [0.49s]                           
Finished <<< champ [0.55s]
Finished <<< champ_navigation [0.51s]
Finished <<< champ_teleop [0.51s]
--- stderr: champ_msgs                             
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c", line 7, in <module>
    from rosidl_typesupport_fastrtps_c import generate_typesupport_fastrtps_c
ModuleNotFoundError: No module named 'rosidl_typesupport_fastrtps_c'
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rosidl_typesupport_c/rosidl_typesupport_c", line 6, in <module>
    from rosidl_typesupport_c import generate_c
ModuleNotFoundError: No module named 'rosidl_typesupport_c'
gmake[2]: *** [CMakeFiles/champ_msgs__rosidl_typesupport_fastrtps_c.dir/build.make:151: rosidl_typesupport_fastrtps_c/champ_msgs/msg/detail/velocities__rosidl_typesupport_fastrtps_c.h] Error 1
gmake[2]: *** [CMakeFiles/champ_msgs__rosidl_typesupport_c.dir/build.make:149: rosidl_typesupport_c/champ_msgs/msg/velocities__type_support.cpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:238: CMakeFiles/champ_msgs__rosidl_typesupport_fastrtps_c.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:290: CMakeFiles/champ_msgs__rosidl_typesupport_c.dir/all] Error 2
Traceback (most recent call last):
  File "/opt/ros/humble/lib/rosidl_typesupport_introspection_c/rosidl_typesupport_introspection_c", line 6, in <module>
    from rosidl_typesupport_introspection_c import generate_c
ModuleNotFoundError: No module named 'rosidl_typesupport_introspection_c'
gmake[2]: *** [CMakeFiles/champ_msgs__rosidl_typesupport_introspection_c.dir/build.make:151: rosidl_typesupport_introspection_c/champ_msgs/msg/detail/velocities__rosidl_typesupport_introspection_c.h] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:264: CMakeFiles/champ_msgs__rosidl_typesupport_introspection_c.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< champ_msgs [1.42s, exited with code 2]

Summary: 5 packages finished [1.73s]
  1 package failed: champ_msgs
  1 package had stderr output: champ_msgs
  3 packages not processed
```

**Comment by physicsfreak963** [comment]
i just deleted the whole workstation and rebuild the problem stopped
